[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.pdo",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mysqli",
  "php83Extensions.mbstring",
  "php83Extensions.curl",
  "php83Extensions.openssl",
  "php83Extensions.gd",
  "php83Extensions.zip",
  "php83Extensions.fileinfo",
  "php83Extensions.session",
  "php83Extensions.tokenizer",
  "php83Extensions.json"
]

[start]
cmd = "php -S 0.0.0.0:$PORT"
