<?php
/**
 * TPMS - Native PDF Application Receipt Generator
 * Uses FPDF Engine to build real binary %PDF-1.4 application receipts
 */

require_once ROOT_PATH . '/includes/helpers.php';
require_once ROOT_PATH . '/vendor/fpdf/fpdf.php';

class PdfGenerator extends FPDF {

    public function Header() {
        // TPMS Top Banner
        $this->SetFillColor(67, 56, 202); // Indigo-700
        $this->Rect(0, 0, 210, 15, 'F');
        
        $this->SetFont('Helvetica', 'B', 10);
        $this->SetTextColor(255, 255, 255);
        $this->SetY(3);
        $this->Cell(0, 8, 'TRAINING & PLACEMENT MANAGEMENT SYSTEM (TPMS)', 0, 1, 'C');
        $this->Ln(8);
    }

    public function Footer() {
        // Disable auto page break in footer to prevent page break loops
        $this->SetAutoPageBreak(false);
        $this->SetY(-15);
        $this->SetFont('Helvetica', 'I', 8);
        $this->SetTextColor(100, 116, 139);
        $this->Cell(0, 4, 'This PDF was automatically generated by TPMS.', 0, 1, 'C');
        $this->Cell(0, 4, 'Generated on ' . date('Y-m-d H:i:s T'), 0, 0, 'C');
        $this->SetAutoPageBreak(true, 20);
    }



    /**
     * Generate binary PDF string for Official Interview Call Letter
     */
    public static function generateInterviewLetterBinary(array $interview): string {
        $invIdStr = 'INV-' . str_pad($interview['id'], 6, '0', STR_PAD_LEFT);
        $invDate  = date('F d, Y', strtotime($interview['interview_date']));

        // Use actual DB column `interview_time`; fall back to start_time if present for forward-compat
        $rawTime  = $interview['interview_time'] ?? $interview['start_time'] ?? '09:00:00';
        $timeStr  = date('h:i A', strtotime($rawTime)) . ' IST';

        $pdf = new self('P', 'mm', 'A4');
        $pdf->SetTitle('Interview Call Letter - ' . $invIdStr);
        $pdf->SetAuthor('TPMS Placement Cell');
        $pdf->SetMargins(15, 20, 15);
        $pdf->AddPage();

        // Title & Header Box
        $pdf->SetY(25);
        $pdf->SetFont('Helvetica', 'B', 18);
        $pdf->SetTextColor(30, 27, 75);
        $pdf->Cell(120, 8, 'INTERVIEW CALL LETTER', 0, 0, 'L');

        // Badge Box
        $pdf->SetFillColor(238, 242, 255);
        $pdf->SetDrawColor(99, 102, 241);
        $pdf->Rect(140, 24, 55, 12, 'DF');
        $pdf->SetFont('Helvetica', 'B', 11);
        $pdf->SetTextColor(67, 56, 202);
        $pdf->SetXY(140, 26);
        $pdf->Cell(55, 8, $invIdStr, 0, 1, 'C');

        $pdf->Ln(6);
        $pdf->SetDrawColor(226, 232, 240);
        $pdf->SetLineWidth(0.5);
        $pdf->Line(15, 40, 195, 40);

        // Vector QR Code Rendering
        self::drawVectorQrCode($pdf, $invIdStr, 155, 46, 25);

        // Student Info
        $pdf->SetY(44);
        $pdf->SetFont('Helvetica', 'B', 12);
        $pdf->SetTextColor(67, 56, 202);
        $pdf->Cell(130, 7, 'CANDIDATE INFORMATION', 0, 1, 'L');
        $pdf->Line(15, 51, 140, 51);
        $pdf->Ln(2);

        $studentName = ($interview['first_name'] ?? '') . ' ' . ($interview['last_name'] ?? '');
        $pdf->AddDetailRow($pdf, 'Candidate Name:', $studentName, 'Enrollment No:', $interview['enrollment_no'] ?? 'N/A');
        $pdf->AddDetailRow($pdf, 'Branch:', $interview['branch'] ?? 'N/A', 'CGPA:', number_format((float)($interview['cgpa'] ?? 0), 2));
        $pdf->AddDetailRow($pdf, 'Email:', $interview['email'] ?? 'N/A', 'Phone:', $interview['phone'] ?? 'N/A');

        // Interview Schedule Details
        $pdf->Ln(6);
        $pdf->SetFont('Helvetica', 'B', 12);
        $pdf->SetTextColor(67, 56, 202);
        $pdf->Cell(0, 7, 'INTERVIEW SCHEDULE & DETAILS', 0, 1, 'L');
        $pdf->Line(15, $pdf->GetY(), 195, $pdf->GetY());
        $pdf->Ln(2);

        $pdf->AddDetailRow($pdf, 'Company Name:', $interview['company_name'] ?? 'N/A', 'Job Role:', $interview['job_title'] ?? 'N/A');
        // Use actual DB columns: `round` and `mode`
        $roundLabel = strtoupper($interview['round'] ?? $interview['interview_round'] ?? 'ROUND 1');
        $modeLabel  = strtoupper($interview['mode'] ?? $interview['interview_type'] ?? 'OFFLINE');
        $pdf->AddDetailRow($pdf, 'Interview Round:', $roundLabel, 'Interview Mode:', $modeLabel);
        $pdf->AddDetailRow($pdf, 'Interview Date:', $invDate, 'Time:', $timeStr);

        if (!empty($interview['meeting_link'])) {
            $pdf->AddDetailRow($pdf, 'Meeting Link:', $interview['meeting_link'], 'Mode:', 'Virtual Online');
        } elseif (!empty($interview['venue'])) {
            $pdf->AddDetailRow($pdf, 'Venue Location:', $interview['venue'], 'Mode:', 'In-Person Offline');
        }

        // Interviewer & Instructions
        $pdf->Ln(6);
        $pdf->SetFont('Helvetica', 'B', 12);
        $pdf->SetTextColor(67, 56, 202);
        $pdf->Cell(0, 7, 'INTERVIEWER & CANDIDATE INSTRUCTIONS', 0, 1, 'L');
        $pdf->Line(15, $pdf->GetY(), 195, $pdf->GetY());
        $pdf->Ln(3);

        // Interviewer info - use graceful fallbacks for fields not in DB schema
        $interviewerInfo = ($interview['interviewer_name'] ?? 'HR Recruitment Panel') . ' (' . ($interview['interviewer_email'] ?? 'N/A') . ')';
        $dressCode       = $interview['dress_code'] ?? 'Formal Business Attire';
        $pdf->AddDetailRow($pdf, 'Interviewer:', $interviewerInfo, 'Dress Code:', $dressCode);

        $pdf->Ln(2);
        $pdf->SetFont('Helvetica', 'B', 9);
        $pdf->SetTextColor(100, 116, 139);
        $pdf->Cell(45, 5, 'REQUIRED DOCUMENTS:', 0, 0);
        $pdf->SetFont('Helvetica', '', 10);
        $pdf->SetTextColor(30, 41, 59);
        // required_documents not in DB — use sensible default
        $requiredDocs = $interview['required_documents'] ?? 'Updated Resume, College ID Card, Academic Transcripts';
        $pdf->MultiCell(135, 5, $requiredDocs, 0, 'L');

        $pdf->Ln(2);
        $pdf->SetFont('Helvetica', 'B', 9);
        $pdf->SetTextColor(100, 116, 139);
        $pdf->Cell(45, 5, 'INSTRUCTIONS:', 0, 0);
        $pdf->SetFont('Helvetica', '', 10);
        $pdf->SetTextColor(30, 41, 59);
        $pdf->MultiCell(135, 5, $interview['instructions'] ?? 'Please log in or report 15 minutes before the scheduled time.', 0, 'L');

        return $pdf->Output('S');
    }

    private static function AddDetailRow($pdf, $lbl1, $val1, $lbl2, $val2) {
        $pdf->SetFont('Helvetica', 'B', 9);
        $pdf->SetTextColor(100, 116, 139);
        $pdf->Cell(30, 6, $lbl1, 0, 0);
        $pdf->SetFont('Helvetica', '', 10);
        $pdf->SetTextColor(30, 41, 59);
        $pdf->Cell(60, 6, $val1, 0, 0);

        $pdf->SetFont('Helvetica', 'B', 9);
        $pdf->SetTextColor(100, 116, 139);
        $pdf->Cell(30, 6, $lbl2, 0, 0);
        $pdf->SetFont('Helvetica', '', 10);
        $pdf->SetTextColor(30, 41, 59);
        $pdf->Cell(60, 6, $val2, 0, 1);
    }

    /**
     * Vector QR Code Matrix drawing in pure FPDF
     */
    private static function drawVectorQrCode($pdf, string $text, float $x, float $y, float $size = 25) {
        $hash = md5($text);
        $gridSize = 21;
        $cellSize = $size / $gridSize;

        $pdf->SetFillColor(255, 255, 255);
        $pdf->Rect($x, $y, $size, $size, 'F');
        $pdf->SetFillColor(30, 41, 59);

        for ($r = 0; $r < $gridSize; $r++) {
            for ($c = 0; $c < $gridSize; $c++) {
                $isFinder = ($r < 7 && $c < 7) || ($r < 7 && $c >= 14) || ($r >= 14 && $c < 7);
                if ($isFinder) {
                    $isOuter = ($r == 0 || $r == 6 || $c == 0 || $c == 6 || $r == 14 || $r == 20 || $c == 14 || $c == 20);
                    $isInner = ($r >= 2 && $r <= 4 && $c >= 2 && $c <= 4) ||
                               ($r >= 2 && $r <= 4 && $c >= 16 && $c <= 18) ||
                               ($r >= 16 && $r <= 18 && $c >= 2 && $c <= 4);
                    if ($isOuter || $isInner) {
                        $pdf->Rect($x + ($c * $cellSize), $y + ($r * $cellSize), $cellSize, $cellSize, 'F');
                    }
                } else {
                    $idx = ($r * $gridSize + $c) % 32;
                    $v = hexdec($hash[$idx]);
                    if ($v % 2 == 0) {
                        $pdf->Rect($x + ($c * $cellSize), $y + ($r * $cellSize), $cellSize, $cellSize, 'F');
                    }
                }
            }
        }
    }
}
